name: Java CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - '**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**'
  workflow_dispatch:
    inputs:
      tags:
        description: 'manual trigger'

jobs:
  build-deploy:
      
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: |
        echo "${{secrets.APPLICATION}}" > src/main/resources/application.yml
        echo "${{secrets.APPLE_LOGIN_PK}}" > src/main/resources/ticketbell.p8
        chmod +x ./gradlew
        ./gradlew build

    - name: deploy
      uses: easingthemes/ssh-deploy@main
      with:
        REMOTE_HOST: ${{secrets.SERVER_HOST}}
        REMOTE_USER: ${{secrets.SERVER_USER}}
        SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
        REMOTE_PORT: 22
        SOURCE: 'build/libs/tinkerbell-0.0.1-SNAPSHOT.jar'
        TARGET: '~'
        SCRIPT_AFTER: |
          pid=$(ps aux | grep "tinkerbell-0.0.1-SNAPSHOT.jar" | grep -v grep | awk '{print $2}')
          if [ -n "$pid" ]; then
            kill -9 $pid  
          fi
          nohup java -jar tinkerbell-0.0.1-SNAPSHOT.jar > logs/access.log 2> logs/error.log &
